!obj:pylearn2.train.Train {
    dataset: !pkl: "%(data_path)s/augmented_train.pkl",
    model: !obj:pylearn2.models.mlp.MLP {
        layers: [
            !obj:pylearn2.models.mlp.Sigmoid {
                layer_name: 'h0',
                dim: %(n_h0)i,
                sparse_init: 15,
            },
            !obj:pylearn2.models.mlp.Sigmoid {
                layer_name: 'h1',
                dim: %(n_h1)i,
                sparse_init: 15
            },
            !obj:pylearn2.models.mlp.Softmax {
                layer_name: 'y',
                n_classes: 43,
                irange: 0.05,
            }
        ],
        nvis: %(nvis)i,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: %(batch_size)i,
        learning_rate: 0.5,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.5,
        },
        monitoring_dataset: {
#            'valid':
#                !pkl: "%(data_path)s/augmented_valid.pkl",
            'test':
                !pkl: "%(data_path)s/augmented_test.pkl",
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: {'h0': 0.5, 'h1': 0.5, 'y': 0.5},
        },
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: %(max_epochs)i
                }
            ]
        }
    },
    extensions: [
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 100,
            final_momentum: 0.75,
        },
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
            channel_name: 'test_y_misclass',
            save_path: "%(save_path)s/dbm_gtsrb_mlp_dropout.pkl",
            store_best_model: True
        },
    ]
}
